parameters:
    mhary_cron.manager.class: Mhary\Bundle\CronBundle\Cron\Manager

services:
    mhary_cron.manager:
        class: "%mhary_cron.manager.class%"
        arguments: ["@logger", "%kernel.root_dir%/console", "%mhary_cron.tasks%"]
        tags:
          - { name: monolog.logger, channel: mhary_cron }
