language: php

php:
  - 7.0
  - 7.1

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=3.2.*
  - SYMFONY_VERSION=3.3.*

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer update --dev

script: phpunit --coverage-text

notifications:
  email:
    - seb.kueck@gmail.com

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
